package luxe.texture3d.app

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.app.Dialog
import android.graphics.Color
import android.graphics.drawable.ColorDrawable
import android.text.Editable
import android.text.TextWatcher
import android.util.LruCache
import android.util.TypedValue
import android.view.*
import android.widget.*
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import kotlin.math.min
import kotlin.math.roundToInt

/** Reusable Hub/editor resource browser foundation. */
class ResourceBrowserView(context:Context,private val onBack:()->Unit,private val showOwnTopBar:Boolean=true,val actions:ResourceBrowserActions?=null):LinearLayout(context){
    data class Item(val id:String,val name:String,val type:String,val subtitle:String="",val thumbnail:File?=null,val modified:Long=0,val source:File?=null)
    private val fs=AppFileSystem(context);private val scale=min(resources.displayMetrics.widthPixels/1600f,resources.displayMetrics.heightPixels/720f).coerceIn(.55f,1.6f)
    private val tree=LinearLayout(context);private val content=LinearLayout(context);private val inspector=LinearLayout(context);private val query=EditText(context);private val cache=object:LruCache<String,Bitmap>(12*1024){override fun sizeOf(k:String,v:Bitmap)=v.byteCount/1024}
    private val favorites=context.getSharedPreferences("resource_favorites",Context.MODE_PRIVATE);private val state=context.getSharedPreferences("resource_browser_state",Context.MODE_PRIVATE);private val trash=TrashManager(context)
    private var allItems:List<Item> = emptyList();private var gridMode=state.getBoolean("grid",true);private var sortMode=state.getString("sort","Name")?:"Name";private var currentTitle=state.getString("section","Projects")?:"Projects";private var selectedId:String?=null

    init{orientation=VERTICAL;setBackgroundColor(0xff121212.toInt());if(showOwnTopBar)addView(topBar(),LayoutParams(-1,u(48)));val body=LinearLayout(context).apply{orientation=HORIZONTAL};tree.orientation=VERTICAL;tree.setPadding(u(5),u(6),u(5),u(6));tree.setBackgroundColor(0xff171717.toInt());body.addView(ScrollView(context).apply{addView(tree)},LayoutParams(u(220),-1));content.orientation=VERTICAL;content.setPadding(u(10),u(8),u(10),u(8));body.addView(content,LayoutParams(0,-1,1f));inspector.orientation=VERTICAL;inspector.setPadding(u(10),u(10),u(10),u(10));inspector.setBackgroundColor(0xff181818.toInt());inspector.visibility=GONE;body.addView(inspector,LayoutParams(u(280),-1));addView(body,LayoutParams(-1,0,1f));buildTree();restoreSection()}

    private fun topBar():View{val row=LinearLayout(context).apply{orientation=HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(u(9),u(5),u(9),u(5));setBackgroundColor(0xff1b1b1b.toInt())};row.addView(button("‹  Back"){onBack()},LayoutParams(u(88),u(36)));row.addView(text("RESOURCE BROWSER",16f,Color.WHITE).apply{setTypeface(typeface,1);setPadding(u(12),0,0,0)},LayoutParams(u(210),-1));query.hint="Search library";query.setSingleLine(true);query.setTextColor(Color.WHITE);query.setHintTextColor(0xff666666.toInt());query.setTextSize(TypedValue.COMPLEX_UNIT_PX,13f*1.25f*scale);query.background=context.getDrawable(R.drawable.hub_field_bg);query.addTextChangedListener(object:TextWatcher{override fun beforeTextChanged(s:CharSequence?,a:Int,b:Int,c:Int){};override fun onTextChanged(s:CharSequence?,a:Int,b:Int,c:Int){state.edit().putString("query",s?.toString().orEmpty()).apply();render()};override fun afterTextChanged(s:Editable?) {}});row.addView(query,LayoutParams(0,u(36),1f));val sort=Spinner(context);sort.adapter=ArrayAdapter(context,android.R.layout.simple_spinner_dropdown_item,listOf("Name","Recently Modified","Type"));sort.onItemSelectedListener=object:AdapterView.OnItemSelectedListener{override fun onItemSelected(p:AdapterView<*>?,v:View?,pos:Int,id:Long){sortMode=listOf("Name","Recently Modified","Type")[pos];state.edit().putString("sort",sortMode).apply();render()};override fun onNothingSelected(p:AdapterView<*>?){}};sort.setSelection(listOf("Name","Recently Modified","Type").indexOf(sortMode).coerceAtLeast(0));row.addView(sort,LayoutParams(u(150),u(36)).apply{leftMargin=u(6)});row.addView(button("▦ / ☰"){gridMode=!gridMode;state.edit().putBoolean("grid",gridMode).apply();render()},LayoutParams(u(72),u(36)).apply{leftMargin=u(6)});return row}

    private fun restoreSection(){when{currentTitle=="Assets"->showAssets();currentTitle=="Library"->showLibraryRoot();currentTitle=="Elements"->showElements();currentTitle=="Recent"->showRecent();currentTitle=="Trash"->showTrash();currentTitle.startsWith("Library / ")->showLibraryCategory(currentTitle.substringAfter("Library / "));else->showProjects()};query.setText(state.getString("query","").orEmpty())}
    private fun buildTree(){tree.removeAllViews();treeHeader("LIBRARY");treeRow("▣","Projects",0){showProjects()};treeRow("◇","Assets",0){showAssets()};treeRow("▤","Library",0){showLibraryRoot()};treeRow("⌘","Elements",0){showElements()};treeRow("◷","Recent",0){showRecent()};treeRow("♲","Trash",0){showTrash()};treeHeader("TYPED LIBRARY");listOf("Texture","Audio","Video","Environment","Animation","Script").forEach{category->treeRow("·",category,1){showLibraryCategory(category)}};treeHeader("ASSET FAMILIES");fs.assets.listFiles()?.filter{it.isDirectory&&File(it,"family.json").isFile}?.sortedBy{it.name.lowercase()}?.take(100)?.forEach{asset->treeRow("›",friendlyAssetName(asset),1){expandAsset(asset)}}}
    private fun expandAsset(asset:File){currentTitle=friendlyAssetName(asset);val family=runCatching{JSONObject(File(asset,"family.json").readText())}.getOrNull()?:return;val list=mutableListOf<Item>();list+=familyItems(asset,family,"geometry","Geometry");list+=familyItems(asset,family,"materials","Material");list+=familyItems(asset,family,"textures","Texture");list+=familyItems(asset,family,"animations","Animation");list+=familyItems(asset,family,"cameras","Camera");list+=familyItems(asset,family,"lights","Light");setItems(list)}

    private fun familyItems(asset:File,family:JSONObject,key:String,type:String):List<Item>{val array=family.optJSONArray(key)?:return emptyList();return (0 until array.length()).mapNotNull{i->val value=array.optJSONObject(i)?:return@mapNotNull null;val name=value.optString("name").ifBlank{"$type ${i+1}"};val detail=when(type){"Geometry"->"${value.optLong("triangleCount")} tris • ${value.optLong("vertexCount")} vertices";"Texture"->value.optString("usage","unknown");else->"${type} index ${value.optInt(type.lowercase()+"Index",value.optInt("index",i))}"};val descriptor=value.optString("libraryPath").takeIf{it.isNotBlank()}?.let{File(fs.library,it)};Item("${asset.name}:$key:$i",name,type,detail,descriptorThumbnail(descriptor),asset.lastModified(),descriptor)}}
    private fun showProjects(){currentTitle="Projects";setItems(fs.projects.listFiles()?.filter{it.isDirectory}?.map{dir->Item(dir.name,dir.name,"Project",relative(dir.lastModified()),File(dir,"thumbnail.png").takeIf{it.isFile},dir.lastModified(),dir)}?:emptyList())}
    private fun showAssets(){currentTitle="Assets";setItems(fs.assets.listFiles()?.filter{it.isDirectory&&File(it,"asset.json").isFile}?.map{dir->val meta=json(File(dir,"asset.json"));Item(dir.name,meta?.optString("displayName")?.substringBeforeLast('.')?.ifBlank{dir.name}?:dir.name,"Asset","${meta?.optLong("triangleCount",0)?:0} tris • ${meta?.optInt("textureCount",0)?:0} textures",File(dir,"thumbnail.png").takeIf{it.isFile},dir.lastModified(),dir)}?:emptyList())}
    private fun showLibraryRoot(){currentTitle="Library";setItems(listOf("Texture","Audio","Video","Environment","Animation","Script").map{category->val dir=libraryDir(category);Item(category,category,"Folder","${dir.listFiles()?.size?:0} items",null,dir.lastModified(),dir)})}
    private fun showLibraryCategory(category:String){currentTitle="Library / $category";val root=libraryDir(category);val ext=when(category){"Texture"->"texture";"Animation"->"anim";else->null};val files=root.walkTopDown().filter{it.isFile&&(ext==null||it.extension.equals(ext,true))}.take(500).map{file->val data=json(file);val name=data?.optString("name")?.ifBlank{file.nameWithoutExtension}?:file.nameWithoutExtension;val type=(data?.optString("type")?.ifBlank{category}?:category).replaceFirstChar{it.uppercase()};val payload=data?.optString("file")?.let{File(file.parentFile,it)};Item(file.absolutePath,name,type,data?.optString("usage").orEmpty(),payload?.takeIf{it.isFile},file.lastModified(),file)}.toList();setItems(files)}
    private fun showElements(){currentTitle="Elements";val items=fs.elements.walkTopDown().filter{it.isFile&&it.extension.equals("ulelement",true)}.map{file->val data=json(file);Item(file.absolutePath,data?.optString("name")?:file.nameWithoutExtension,"Ulelement","Family Element",File(file.parentFile,"thumbnail.png").takeIf{it.isFile},file.lastModified(),file)}.toList();setItems(items)}
    private fun showRecent(){currentTitle="Recent";setItems((assetItems()+projectItems()).sortedByDescending{it.modified}.take(100))}
    private fun showTrash(){currentTitle="Trash";setItems(trash.entries().map{dir->val meta=json(File(dir,"trash.json"));Item(dir.absolutePath,meta?.optString("name")?:dir.name,"Trash",meta?.optString("type").orEmpty(),null,dir.lastModified(),dir)})}
    private fun assetItems():List<Item>{showAssets();return allItems}
    private fun projectItems():List<Item>{showProjects();return allItems}

    private fun setItems(items:List<Item>){allItems=items;selectedId=null;inspector.visibility=GONE;state.edit().putString("section",currentTitle).apply();render()}
    private fun render(){content.removeAllViews();content.addView(text("$currentTitle   •   ${filtered().size} items",13f,0xffdddddd.toInt()).apply{setTypeface(typeface,1)},LayoutParams(-1,u(34)));val holder=if(gridMode)grid(filtered())else list(filtered());content.addView(ScrollView(context).apply{addView(holder)},LayoutParams(-1,0,1f))}
    private fun filtered():List<Item>{val q=query.text.toString().trim().lowercase();val source=if(q.isBlank())allItems else allItems.filter{it.name.lowercase().contains(q)||it.type.lowercase().contains(q)||it.subtitle.lowercase().contains(q)};return when(sortMode){"Recently Modified"->source.sortedByDescending{it.modified};"Type"->source.sortedWith(compareBy<Item>{it.type}.thenBy{it.name});else->source.sortedBy{it.name.lowercase()}}}
    private fun grid(items:List<Item>):View{val grid=GridLayout(context).apply{columnCount=if(resources.displayMetrics.widthPixels>=1400)5 else 4};items.forEach{grid.addView(card(it),GridLayout.LayoutParams().apply{width=u(190);height=u(180);setMargins(0,0,u(9),u(9))})};return grid}
    private fun list(items:List<Item>):View=LinearLayout(context).apply{orientation=VERTICAL;items.forEach{addView(listRow(it),LayoutParams(-1,u(62)).apply{bottomMargin=u(4)})}}
    private fun card(item:Item)=LinearLayout(context).apply{orientation=VERTICAL;setPadding(u(6),u(6),u(6),u(6));setBackgroundResource(if(selectedId==item.id)R.drawable.hub_nav_selected else R.drawable.hub_card_bg);setOnClickListener{select(item)};addView(image(item),LayoutParams(-1,0,1f));addView(text(item.name,11f,0xffdddddd.toInt()).apply{setTypeface(typeface,1)},LayoutParams(-1,u(24)));addView(text("${item.type}  •  ${item.subtitle}",9f,0xff777777.toInt()),LayoutParams(-1,u(19)))}
    private fun listRow(item:Item)=LinearLayout(context).apply{orientation=HORIZONTAL;gravity=Gravity.CENTER_VERTICAL;setPadding(u(8),u(5),u(8),u(5));setBackgroundResource(if(selectedId==item.id)R.drawable.hub_nav_selected else R.drawable.hub_project_row);setOnClickListener{select(item)};addView(image(item),LayoutParams(u(48),u(48)));addView(LinearLayout(context).apply{orientation=VERTICAL;addView(text(item.name,12f,0xffdddddd.toInt()));addView(text("${item.type} • ${item.subtitle}",9f,0xff777777.toInt()))},LayoutParams(0,-1,1f).apply{leftMargin=u(9)})}
    private fun image(item:Item)=ImageView(context).apply{val bitmap=item.thumbnail?.let(::bitmap);if(bitmap!=null){setImageBitmap(bitmap);scaleType=ImageView.ScaleType.CENTER_CROP}else{setImageResource(if(item.type=="Project")R.drawable.luxe_launcher else R.drawable.thumb_empty);scaleType=ImageView.ScaleType.CENTER_INSIDE;setPadding(u(16),u(10),u(16),u(10))}}
    private fun bitmap(file:File):Bitmap?{if(!file.isFile)return null;cache.get(file.absolutePath)?.let{return it};val b=BitmapFactory.Options().apply{inJustDecodeBounds=true};BitmapFactory.decodeFile(file.absolutePath,b);var sample=1;while(b.outWidth/sample>512||b.outHeight/sample>512)sample*=2;return BitmapFactory.decodeFile(file.absolutePath,BitmapFactory.Options().apply{inSampleSize=sample})?.also{cache.put(file.absolutePath,it)}}

    private fun select(item:Item){selectedId=item.id;render();buildInspector(item)}
    private fun buildInspector(item:Item){
        inspector.removeAllViews();inspector.visibility=VISIBLE
        inspector.addView(text("INSPECTOR",10f,0xff777777.toInt()),LayoutParams(-1,u(28)))
        inspector.addView(image(item),LayoutParams(-1,u(145)))
        inspector.addView(text(item.name,15f,0xffeeeeee.toInt()).apply{setTypeface(typeface,1)},LayoutParams(-1,u(34)))
        inspector.addView(text(item.type,11f,0xff79a5d2.toInt()),LayoutParams(-1,u(23)))
        inspector.addView(text(item.subtitle.ifBlank{"No additional summary"},10f,0xff999999.toInt()),LayoutParams(-1,u(36)))
        val path=item.source?.absolutePath.orEmpty()
        when(item.type){
            "Asset"->inspector.addView(actionButton("Add to Scene"){actions?.onAddToScene(path)},LayoutParams(-1,u(36)).apply{topMargin=u(6)})
            "Project"->inspector.addView(actionButton("Open Project"){actions?.onOpenProject(path)},LayoutParams(-1,u(36)).apply{topMargin=u(6)})
            "Ulelement"->inspector.addView(actionButton("Add Entire Element"){actions?.onAddToProject(path)},LayoutParams(-1,u(36)).apply{topMargin=u(6)})
            "Texture","Animation","Audio","Video","Environment","Script"->inspector.addView(actionButton("Add to Project"){actions?.onAddToProject(path)},LayoutParams(-1,u(36)).apply{topMargin=u(6)})
        }
        inspector.addView(actionButton(if(isFavorite(item))"★  Favorite" else "☆  Add Favorite"){toggleFavorite(item)},LayoutParams(-1,u(34)).apply{topMargin=u(5)})
        inspector.addView(actionButton("Validate"){showValidation(item)},LayoutParams(-1,u(34)).apply{topMargin=u(4)})
        if(item.type in setOf("Asset","Project","Texture","Animation","Ulelement"))inspector.addView(actionButton("Rename"){showRename(item)},LayoutParams(-1,u(34)).apply{topMargin=u(4)})
        if(item.type=="Project")inspector.addView(actionButton("Rebuild ULX"){rebuildProject(item)},LayoutParams(-1,u(34)).apply{topMargin=u(4)})
        if(item.type in setOf("Asset","Project","Ulelement"))inspector.addView(actionButton("Move to Trash"){confirmTrash(item)},LayoutParams(-1,u(34)).apply{topMargin=u(4)})
        if(item.type=="Trash"){inspector.addView(actionButton("Restore"){restore(item)},LayoutParams(-1,u(34)).apply{topMargin=u(4)});inspector.addView(actionButton("Delete Permanently"){confirmDelete(item)},LayoutParams(-1,u(34)).apply{topMargin=u(4)})}
        inspector.addView(Space(context),LayoutParams(1,0,1f));inspector.addView(button("Close Inspector"){selectedId=null;inspector.visibility=GONE;render()},LayoutParams(-1,u(34)))
    }

    private fun actionButton(value:String,click:()->Unit)=button(value,click)
    private fun isFavorite(item:Item)=favorites.getBoolean(item.id,false)
    private fun toggleFavorite(item:Item){favorites.edit().putBoolean(item.id,!isFavorite(item)).apply();buildInspector(item)}
    private fun showValidation(item:Item){val result=when(item.type){"Asset"->item.source?.let(ResourceValidation::asset);"Project"->item.source?.let(ResourceValidation::project);"Ulelement"->item.source?.let(ResourceValidation::ulelement);else->item.source?.takeIf{it.isFile}?.let(ResourceValidation::descriptor)}?:ResourceValidation.Result("Unknown",listOf("No validator for this item"));messageDialog("Validation: ${result.status}",result.messages.joinToString("\n").ifBlank{"No issues found"})}
    private fun showRename(item:Item){val dialog=Dialog(context);dialog.requestWindowFeature(Window.FEATURE_NO_TITLE);val box=LinearLayout(context).apply{orientation=VERTICAL;setPadding(u(16),u(14),u(16),u(14));setBackgroundResource(R.drawable.hub_dialog_bg)};box.addView(text("Rename ${item.type}",15f,Color.WHITE),LayoutParams(-1,u(34)));val input=EditText(context).apply{setText(item.name);setTextColor(Color.WHITE);setSingleLine(true);background=context.getDrawable(R.drawable.hub_field_bg)};box.addView(input,LayoutParams(-1,u(42)));val row=LinearLayout(context).apply{orientation=HORIZONTAL;gravity=Gravity.END};row.addView(button("Cancel"){dialog.dismiss()},LayoutParams(u(86),u(36)));row.addView(button("Save"){val name=input.text.toString().trim();if(name.isNotBlank()){rename(item,name);dialog.dismiss()}},LayoutParams(u(86),u(36)).apply{leftMargin=u(6)});box.addView(row,LayoutParams(-1,u(44)));dialog.setContentView(box);dialog.show();dialog.window?.apply{setBackgroundDrawable(ColorDrawable(Color.TRANSPARENT));setLayout((resources.displayMetrics.widthPixels*.42f).toInt(),ViewGroup.LayoutParams.WRAP_CONTENT)}}
    private fun rename(item:Item,newName:String){val source=item.source?:return;runCatching{when(item.type){"Asset"->{val a=File(source,"asset.json");val j=JSONObject(a.readText()).put("displayName",newName);a.writeText(j.toString());File(source,"family.json").takeIf{it.isFile}?.let{f->f.writeText(JSONObject(f.readText()).put("name",newName).toString(2))}};"Project"->{val f=File(source,"project.json");f.writeText(JSONObject(f.readText()).put("name",newName).toString());ProjectPackageManager.rebuild(source)};"Ulelement","Texture","Animation"->{val f=if(source.isDirectory)source.listFiles()?.firstOrNull{it.extension in setOf("ulelement","texture","anim")}?:source else source;f.writeText(JSONObject(f.readText()).put("name",newName).toString(2))}}}.onFailure{messageDialog("Rename failed",it.message?:"Unknown error")};refreshCurrent()}
    private fun rebuildProject(item:Item){runCatching{ProjectPackageManager.rebuild(item.source?:error("Project unavailable"))}.onSuccess{messageDialog("ULX rebuilt",it.name)}.onFailure{messageDialog("Rebuild failed",it.message?:"Unknown error")}}
    private fun confirmTrash(item:Item)=confirmDialog("Move to Trash?","${item.name} can be restored later."){val source=item.source?:return@confirmDialog;val target=if(item.type=="Ulelement"&&source.isFile)source.parentFile else source;runCatching{trash.move(target,item.type,item.name)}.onFailure{messageDialog("Trash failed",it.message?:"Unknown error")};refreshCurrent()}
    private fun restore(item:Item){runCatching{trash.restore(item.source?:error("Trash item missing"))}.onFailure{messageDialog("Restore failed",it.message?:"Unknown error")};showTrash();buildTree()}
    private fun confirmDelete(item:Item)=confirmDialog("Delete permanently?","This cannot be undone."){runCatching{trash.deletePermanently(item.source?:error("Trash item missing"))};showTrash()}
    private fun refreshCurrent(){buildTree();when{currentTitle=="Projects"->showProjects();currentTitle=="Assets"->showAssets();currentTitle=="Elements"->showElements();currentTitle=="Recent"->showRecent();currentTitle=="Trash"->showTrash();currentTitle.startsWith("Library / ")->showLibraryCategory(currentTitle.substringAfter("Library / "));else->render()}}
    private fun confirmDialog(title:String,message:String,yes:()->Unit){val dialog=Dialog(context);dialog.requestWindowFeature(Window.FEATURE_NO_TITLE);val box=LinearLayout(context).apply{orientation=VERTICAL;setPadding(u(16),u(14),u(16),u(14));setBackgroundResource(R.drawable.hub_dialog_bg);addView(text(title,15f,Color.WHITE),LayoutParams(-1,u(34)));addView(text(message,11f,0xffaaaaaa.toInt()),LayoutParams(-1,u(44)))};val row=LinearLayout(context).apply{orientation=HORIZONTAL;gravity=Gravity.END};row.addView(button("Cancel"){dialog.dismiss()},LayoutParams(u(86),u(36)));row.addView(button("Yes"){dialog.dismiss();yes()},LayoutParams(u(86),u(36)).apply{leftMargin=u(6)});box.addView(row);dialog.setContentView(box);dialog.show();dialog.window?.setBackgroundDrawable(ColorDrawable(Color.TRANSPARENT))}
    private fun messageDialog(title:String,message:String){val dialog=Dialog(context);dialog.requestWindowFeature(Window.FEATURE_NO_TITLE);val box=LinearLayout(context).apply{orientation=VERTICAL;setPadding(u(16),u(14),u(16),u(14));setBackgroundResource(R.drawable.hub_dialog_bg);addView(text(title,15f,Color.WHITE),LayoutParams(-1,u(34)));addView(ScrollView(context).apply{addView(text(message,11f,0xffaaaaaa.toInt()).apply{setPadding(0,u(5),0,u(5))})},LayoutParams(-1,u(130)));addView(button("Close"){dialog.dismiss()},LayoutParams(-1,u(36)))};dialog.setContentView(box);dialog.show();dialog.window?.apply{setBackgroundDrawable(ColorDrawable(Color.TRANSPARENT));setLayout((resources.displayMetrics.widthPixels*.48f).toInt(),ViewGroup.LayoutParams.WRAP_CONTENT)}}

    private fun treeHeader(value:String){tree.addView(text(value,9f,0xff666666.toInt()).apply{setPadding(u(8),u(8),0,0)},LayoutParams(-1,u(28)))}
    private fun treeRow(icon:String,title:String,depth:Int,click:()->Unit){tree.addView(text("$icon   $title",11f,0xffb8b8b8.toInt()).apply{setPadding(u(10+depth*14),0,u(5),0);setOnClickListener{click()}},LayoutParams(-1,u(36)))}
    private fun button(value:String,click:()->Unit)=text(value,11f,0xffdddddd.toInt()).apply{gravity=Gravity.CENTER;setBackgroundResource(R.drawable.hub_secondary_button);setOnClickListener{click()}}
    private fun text(value:String,size:Float,color:Int)=TextView(context).apply{text=value;setTextSize(TypedValue.COMPLEX_UNIT_PX,size*1.25f*scale);setTextColor(color);gravity=Gravity.CENTER_VERTICAL;includeFontPadding=false}
    private fun libraryDir(category:String)=when(category){"Texture"->fs.libraryTextures;"Audio"->fs.libraryAudio;"Video"->fs.libraryVideo;"Environment"->fs.libraryEnvironment;"Animation"->fs.libraryAnimation;"Script"->fs.libraryScript;else->fs.library}
    private fun descriptorThumbnail(file:File?):File?{if(file==null)return null;val data=json(file)?:return null;return data.optString("file").takeIf{it.isNotBlank()}?.let{File(file.parentFile,it)}?.takeIf{it.isFile}}
    private fun json(file:File)=runCatching{JSONObject(file.readText())}.getOrNull()
    private fun friendlyAssetName(dir:File)=json(File(dir,"asset.json"))?.optString("displayName")?.substringBeforeLast('.')?.ifBlank{dir.name}?:dir.name
    private fun relative(time:Long):String{val d=(System.currentTimeMillis()-time).coerceAtLeast(0);return if(d<86_400_000)"Modified ${d/3_600_000}h ago" else "Modified ${d/86_400_000}d ago"}
    private fun u(v:Int)=(v*scale).roundToInt()
}
